color:
  when: auto
  theme: custom

blocks:
  - permission
  - user
  - group
  - size
  - date
  - name

date: relative

icons:
  theme: fancy
  separator: ''
  when: never

indicators: true

total-size: false

hyperlink: auto

symlink-arrow: " "

display: almost-all
