[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.js", "*.json", "*.md", "*.yml",]

[formatter.bash]
command = "shfmt"
options = ["--language-dialect", "bash", "--write", "--indent", "2",]
includes = [".envrc", "*.bash",]

[formatter.fish]
command = "fish_indent"
options = ["--write",]
includes = ["*.fish",]

[formatter.nix]
command = "bash"
options = [
    "-euc",
    """
deadnix --edit "$@"
for file in "$@"; do
  statix fix "$file"
  statix check "$file"
done
alejandra "$@"
    """,
    "--",
]
includes = [ "*.nix" ]

[formatter.justfile]
command = "just"
options = ["--unstable", "--fmt", "--justfile",]
includes = ["justfile",]

[formatter.lua]
command = "stylua"
options = ["--column-width", "100",]
includes = ["*.lua",]

[formatter.go]
command = "gofmt"
options = ["-w"]
includes = ["*.go"]

[formatter.python]
command = "black"
includes = ["*.py"]
