- defaults:
    link:
      create: true
    shell:
      stdin: true
      stdout: true
      stderr: true

- clean:
    ~/.config:
        recursive: true
    # Dotbot fails if I don't add a slash after '~'
    ~/: {}
    ~/.local/bin: {}
    ~/.local/share/applications: {}
    ~/.dotfiles/.git/hooks: {}

- link:
    ~/.dotfiles/.git/hooks/post-merge: meta/update_modules.sh
