name: Cache Build Results
on:
  push:
    paths:
      - '.github/workflows/cache-build-results.yml'
      - 'flake.nix'
      - 'flake.lock'
      - 'flake-modules/**'
      - 'dotfiles/**'
    branches:
      - master
env:
  HOME: ${{ github.workspace }}
jobs:
  add-to-cachix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO: yabai won't build with macos-latest, which is currently an alias to macos-12
        os: [ubuntu-latest, macos-11]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          path: '.dotfiles'
      - uses: DeterminateSystems/nix-installer-action@main
        # home-manager's `mkOutOfStoreSymlink` doesn't work on nix v2.19 so I'm pinning v2.18:
        # https://github.com/nix-community/home-manager/issues/4692
        # https://github.com/NixOS/nix/issues/9579
        with:
          nix-installer-tag: v0.13.1
      - uses: cachix/cachix-action@v14
        with:
          name: bigolu
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          # This isn't working right now:
          # https://github.com/cachix/cachix-action/issues/169
          useDaemon: false
      - run: nix run .#nix -- build --show-trace
        working-directory: './.dotfiles'
