name: Cache Build Results
on:
  push:
    paths:
      - '**.nix'
      - '.github/workflows/cache-build-results.yml'
    branches:
      - master
env:
  HOME: ${{ github.workspace }}
jobs:
  add-to-cachix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          path: '.dotfiles'
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: bigolu
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build --show-trace --update-input my-overlay
        working-directory: './.dotfiles'
