name: Cache Build Results
on:
  push:
    paths:
      - '.github/workflows/cache-build-results.yml'
      - 'flake.nix'
      - 'flake.lock'
      - 'flake-modules/**'
    branches:
      - master
env:
  HOME: ${{ github.workspace }}
jobs:
  add-to-cachix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          path: '.dotfiles'
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v12
        with:
          name: bigolu
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build --show-trace
        working-directory: './.dotfiles'
