name: Cache Build Results
on:
  push:
    paths:
      - '.github/workflows/cache-build-results.yml'
      - 'flake.nix'
      - 'flake.lock'
      - 'flake-modules/**'
      - 'dotfiles/**'
    branches:
      - master
env:
  HOME: ${{ github.workspace }}
jobs:
  add-to-cachix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO: yabai only builds on macos-11, before this I was using macos-latest, an alias to
        # macos-12
        os: [ubuntu-latest, macos-11]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          path: '.dotfiles'
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: bigolu
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          # This isn't working right now:
          # https://github.com/cachix/cachix-action/issues/169
          useDaemon: false
      - run: nix build --show-trace
        working-directory: './.dotfiles'
